### ISSUE TITLE
Position 'X' and 'Y' have too low possible maximum values

### ISSUE THREAD

**Issue by echteFerux** [fossfreedom/desktop-art#4]
The position of the Rhythmbox Destkop Art plugin can be changed by pressing Alt + moving around the Art, but the new location is not saved. In order to do so, I need to adapt the settings using either Gconf or the preferences. (like you already noticed, there's a bug when editing these preferences too much).

However, when using multiple screens, the maximum of 1000 pixels as Y component is too low when using multiple screens and stacking the screens on top of each other. The X-component might have the same issue when putitng the screens next to each other.

System: Ubuntu 14.04 x64 Unity
##

**Comment by TechSupport26** [comment]
I am not sure if this fits here perfectly but when I change the size or x and y positions with the buttons more than two times, Rhythmbox crashes and I get the following.

```shell
Segmentation fault (core dumped)
``` 

here is a backtrace

```shell
(gdb) bt
#0  0x00007ffff7d4607e in g_slice_alloc () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff7d226e6 in g_list_prepend () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff7608c1e in gtk_main_do_event () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#3  0x00007ffff6b97815 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007ffff6ba6209 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007ffff6ba7d22 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007ffff6ba7f18 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#7  0x00007ffff7c8a5a9 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff7ca3bbf in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff7ca3dbf in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6ba037e in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#11 0x00007ffff6b8c7e7 in ?? () from /lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007ffff7d2819a in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff7d2767f in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff7d27a38 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff7d27acc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6efd65d in g_application_run () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007ffff7e50046 in rb_application_run () from /lib/x86_64-linux-gnu/librhythmbox-core.so.10
#18 0x0000555555555203 in main ()

```
